# Basic
title: ☁️ོSemper fi
subtitle: find the re
welcome_message: <a href="" target="_blank"></a>
description: 嗨，我是封硕 (@Dejavu_Memory)，一名来自中国的区块链研习者,探求区块链新世界的可能性。
creator: <a href="SemperFiFeng"></a>

url: "http://SemperFiFeng.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'https:baidu.com'}
    - {title: 关于, description: 了解更多关于我, url: 'http://baidu.com/'}
    - {title: 订阅, description: 邮件订阅本站, url: '//baidu.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Semper fi
    # duoshuo:
# Social
social:
    weibo: Semper fi
    github: Semper fi
    twitter: Semper fi
    gplus: 107
    mail: fengshuo.dr@gmail.com

# Google Analytics
ga:
    id:
    host: fengshuo.github.io
